/**
 * Payment provider adapter — the ONLY module in the codebase that imports the
 * `stripe` SDK or knows stripe.com exists.
 *
 * WHY an adapter at all: business logic (BillingService, StripeWebhookService)
 * must be testable without network access or live API keys. Everything below is
 * a thin pass-through — deliberately NOT a generic "payments interface" with
 * provider-neutral types. Stripe's own vocabulary (status strings, price ids,
 * checkout sessions) is used verbatim all the way into the database, because a
 * translation layer for a second provider that does not exist is exactly the
 * abstraction this codebase's rules forbid. If a second provider ever lands, the
 * seam is here and the call sites already go through it.
 *
 * ── TWO SEPARATELY TESTABLE HALVES ───────────────────────────────────────────
 *   1. verifyWebhookSignature(rawBody, signatureHeader) — HMAC only. Tested with
 *      real signatures generated by the SDK's own generateTestHeaderString(),
 *      so the verification path is exercised for real, offline.
 *   2. createCheckoutSession / createPortalSession / listInvoices — network
 *      calls. Replaced wholesale in tests via setBillingProvider().
 * The webhook route verifies (1) then hands a plain event OBJECT to
 * StripeWebhookService, which is pure DB logic — so event PROCESSING can be
 * tested with no signature and no adapter at all.
 *
 * ── CREDENTIALS ──────────────────────────────────────────────────────────────
 * STRIPE_SECRET_KEY / STRIPE_WEBHOOK_SECRET are read LAZILY, per call, not at
 * require() time: the module must load in tests and in a dev boot that has no
 * Stripe configured. A missing key throws only when a real API call is actually
 * attempted.
 */
const Stripe = require('stripe');

let stripeClient = null;
function stripe() {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) throw new Error('STRIPE_SECRET_KEY is not configured');
  // Cached across calls, but re-created if the key changes (tests, key rotation).
  if (!stripeClient || stripeClient._frameworkKey !== key) {
    stripeClient = new Stripe(key);
    stripeClient._frameworkKey = key;
  }
  return stripeClient;
}

function webhookSecret() {
  const secret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!secret) throw new Error('STRIPE_WEBHOOK_SECRET is not configured');
  return secret;
}

// ── The real adapter ──────────────────────────────────────────────────────────

const realProvider = {
  /**
   * @param {Buffer|string} rawBody  the UNPARSED request body (express.raw)
   * @param {string} signatureHeader value of the `stripe-signature` header
   * @returns {object} the verified Stripe event
   * @throws  when the signature is absent, malformed, wrong, or outside the
   *          replay tolerance — the caller must answer 400 and process nothing.
   */
  verifyWebhookSignature(rawBody, signatureHeader) {
    // constructEvent needs the exact bytes Stripe signed. JSON.parse →
    // JSON.stringify round-tripping changes key order and whitespace and breaks
    // the HMAC, which is why the route mounts express.raw() ahead of
    // express.json() in server.js.
    return stripe().webhooks.constructEvent(rawBody, signatureHeader, webhookSecret());
  },

  async createCheckoutSession({ organizationId, planKey, priceId, customerId, customerEmail, successUrl, cancelUrl }) {
    const session = await stripe().checkout.sessions.create({
      mode: 'subscription',
      line_items: [{ price: priceId, quantity: 1 }],
      success_url: successUrl,
      cancel_url:  cancelUrl,
      ...(customerId ? { customer: customerId } : { customer_email: customerEmail }),
      // client_reference_id is how checkout.session.completed is mapped back to a
      // tenant: at checkout time there is no stripeSubscriptionId yet, and the
      // customer may be brand new. Also mirrored into subscription metadata so a
      // later customer.subscription.* event can resolve the org even if the
      // local stripeCustomerId write lost a race with the webhook.
      client_reference_id: organizationId,
      // planKey rides along so checkout.session.completed can name the plan
      // without expanding line items: the session's own price id is only
      // reachable via a second API call, and the webhook handler must stay a
      // pure function of the event payload to remain testable offline.
      subscription_data: { metadata: { organizationId, planKey } },
      metadata: { organizationId, planKey },
    });
    return { id: session.id, url: session.url };
  },

  async createPortalSession({ customerId, returnUrl }) {
    const session = await stripe().billingPortal.sessions.create({
      customer:   customerId,
      return_url: returnUrl,
    });
    return { id: session.id, url: session.url };
  },

  /**
   * SCOPE: a single most-recent page, no cursor pagination. Invoice history is
   * Stripe's job — the Billing Portal shows the full, paginated, downloadable
   * list — so this exists only to render a short "recent invoices" strip.
   * Deep pagination is a deliberate follow-up, not an oversight.
   */
  async listInvoices({ customerId, limit = 10 }) {
    const invoices = await stripe().invoices.list({ customer: customerId, limit });
    return invoices.data.map((inv) => ({
      id:          inv.id,
      number:      inv.number,
      status:      inv.status,
      amountPaid:  inv.amount_paid,
      currency:    inv.currency,
      createdAt:   inv.created ? new Date(inv.created * 1000) : null,
      hostedUrl:   inv.hosted_invoice_url,
      pdfUrl:      inv.invoice_pdf,
    }));
  },
};

// ── Swappable instance ────────────────────────────────────────────────────────
// Tests call setBillingProvider({...}) to inject a fake. Kept as a module-level
// binding accessed through getBillingProvider() so services pick up the fake even
// though they required this module at import time.
let current = realProvider;

function getBillingProvider()      { return current; }
function setBillingProvider(fake)  { current = fake || realProvider; }
function resetBillingProvider()    { current = realProvider; }

module.exports = {
  getBillingProvider,
  setBillingProvider,
  resetBillingProvider,
  realProvider,
};
